name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: 'TEST: Values'
        id: glob-values
        uses: ./.
        with:
          pattern: |
            {a|c}.txt
          values: |
            a
            b
            c
      - name: FAILED
        if: glob-values != "a\nb"
        run: |
          echo "Matches:"
          echo "${{ steps.glob-values.outputs.matches }}"
          exit 1
